version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: wordpressdb
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - wordpress:/var/www/html

  wordpressdb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - database:/var/lib/mysql

volumes:
  wordpress:
  database:
