version: '3.7'

services:
   db:
     image: mysql
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
        MYSQL_ROOT_PASSWORD: somepassword
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8080:80"
     restart: always
     environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
     volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - wordpress:/var/www/html
volumes:
    db_data:
      driver: local
    wordpress:
      driver: local
